---
slug: blended_agile_delivery
filename: blended_agile_delivery
title: Blended Agile Delivery
subtitle: The art of rapid, repeatable & predictable software delivery
description: TODO
author: Gary Green, Helen Martin, Tom Walton, Austen Bell
copyright: 2017
uuid: b9beca7f-ff47-45c0-b4d7-dbc346b4be74
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
