---
slug: blended_agile_delivery
filename: blended_agile_delivery
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2017
uuid: b9beca7f-ff47-45c0-b4d7-dbc346b4be74
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
